FROM scratch
MAINTAINER Arun Neelicattu <arun.neelicattu@gmail.com>

ADD cayley /cayley
ADD templates /templates
ADD static /static
ADD docs /docs
ADD data /data
ADD tmp /tmp
ADD log /log

VOLUME ["/data", "/tmp", "/log"]
EXPOSE 64210

ENTRYPOINT ["/cayley"]
